/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ..\..\public\models\totoro.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Totoro = (props) => {
  const { nodes, materials } = useGLTF('/models/totoro.gltf')
  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes.Body.geometry} material={materials.skin} position={[0, 12.5, 0]} scale={7.42} castShadow>
        <mesh geometry={nodes.Arms.geometry} material={materials.skin} position={[0.89, -0.2, -0.12]} rotation={[0, 0, 0.19]} scale={0.34} castShadow>
          <mesh geometry={nodes.Claws_arms.geometry} material={materials.claws} position={[-0.04, -2.46, -0.48]} rotation={[0.05, 0.25, 0.06]} scale={0.28} castShadow/>
        </mesh>
        <mesh geometry={nodes.Belly.geometry} material={materials.belly}>
          <mesh geometry={nodes.Marks_belly.geometry} material={materials.skin} position={[0, -0.11, 0.88]} rotation={[-0.52, 0, 0]} scale={[0.11, 0.04, 0.01]}  castShadow/>
          <mesh geometry={nodes.Marks_belly001.geometry} material={materials.skin} position={[0.43, -0.3, 0.86]} rotation={[-0.42, 0.43, 0.18]} scale={[0.11, 0.04, 0.01]}  castShadow/>
        </mesh>
        <mesh geometry={nodes.Ears.geometry} material={materials.skin} position={[0.44, 0.93, 0]} rotation={[0, 0, -0.27]} scale={0.05}  castShadow/>
        <group position={[0.46, 0.32, 0.78]} rotation={[-0.24, 0.63, -0.11]} scale={[0.11, 0.11, 0.05]}>
          <mesh geometry={nodes.Sphere.geometry} material={materials['eyes | sclera']} castShadow/>
          <mesh geometry={nodes.Sphere_1.geometry} material={materials['eyes | pupil']} castShadow/>
        </group>
        <mesh geometry={nodes.Feet.geometry} material={materials.skin} position={[0.26, -1.5, -0.12]} rotation={[0, -1.19, 1.63]} scale={[0.24, 0.18, 0.24]} castShadow>
          <mesh geometry={nodes.Claws_feet.geometry} material={materials.claws} position={[-0.72, -2.4, -0.04]} rotation={[0.12, 0.19, -0.22]} scale={[0.36, 0.58, 0.32]} castShadow/>
        </mesh>
        <mesh geometry={nodes.Leaf_hat.geometry} material={materials['leaf | body']} position={[0, 0.92, 0]} scale={0.41}>
          <mesh geometry={nodes.Stalk.geometry} material={materials['leaf | stalk']} position={[0.01, 0.41, -1.3]} rotation={[0.08, 0, 0]} scale={[0.15, 0.08, 0.59]} castShadow/>
        </mesh>
        <mesh geometry={nodes.Nose.geometry} material={materials.nose} position={[0, 0.38, 0.8]} rotation={[1.01, 0, 0]} scale={[0.13, 0.12, 0.09]} castShadow/>
        <mesh geometry={nodes.Tail.geometry} material={materials.skin} position={[0, -1.34, -0.86]} scale={[0.31, 0.31, 0.4]}  castShadow/>
        <mesh geometry={nodes.Whiskers.geometry} material={materials.whiskers} position={[0.42, 0.2, 0.4]} rotation={[0, 0.35, -0.05]} scale={0.04} castShadow/>
      </mesh>
    </group>
  )
}
export default Totoro
useGLTF.preload('/models/totoro.gltf')
